"""empty message

Revision ID: 289f4011b0c2
Revises: 91ab41d89643
Create Date: 2022-08-30 07:58:23.834773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289f4011b0c2'
down_revision = '91ab41d89643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toolbox', sa.Column('tools', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'toolbox', 'tool', ['tools'], ['tool_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'toolbox', type_='foreignkey')
    op.drop_column('toolbox', 'tools')
    # ### end Alembic commands ###
