"""empty message

Revision ID: 62c03f816fde
Revises: 7030f6490fa5
Create Date: 2022-08-23 22:19:06.955485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c03f816fde'
down_revision = '7030f6490fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tool_toolboxid_fkey', 'tool', type_='foreignkey')
    op.drop_column('tool', 'toolboxid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('toolboxid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tool_toolboxid_fkey', 'tool', 'toolbox', ['toolboxid'], ['toolbox_id'])
    # ### end Alembic commands ###
