"""empty message

Revision ID: 7030f6490fa5
Revises: 
Create Date: 2022-08-22 09:09:06.450293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7030f6490fa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toolbox',
    sa.Column('toolbox_id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('toolbox_id')
    )
    op.create_table('tool',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('toolboxid', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=20), nullable=True),
    sa.Column('tool_brand', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['toolboxid'], ['toolbox.toolbox_id'], ),
    sa.PrimaryKeyConstraint('tool_id')
    )
    op.create_index(op.f('ix_tool_tool_brand'), 'tool', ['tool_brand'], unique=False)
    op.create_index(op.f('ix_tool_tool_name'), 'tool', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_tool_name'), table_name='tool')
    op.drop_index(op.f('ix_tool_tool_brand'), table_name='tool')
    op.drop_table('tool')
    op.drop_table('toolbox')
    # ### end Alembic commands ###
