"""empty message

Revision ID: 91ab41d89643
Revises: a3b1174de0d5
Create Date: 2022-08-23 22:25:24.541755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ab41d89643'
down_revision = 'a3b1174de0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('toolboxid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tool', 'toolbox', ['toolboxid'], ['toolbox_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool', type_='foreignkey')
    op.drop_column('tool', 'toolboxid')
    # ### end Alembic commands ###
