"""empty message

Revision ID: a3b1174de0d5
Revises: 62c03f816fde
Create Date: 2022-08-23 22:22:46.238463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b1174de0d5'
down_revision = '62c03f816fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool', 'quantity')
    # ### end Alembic commands ###
