"""empty message

Revision ID: ee440e418780
Revises: 
Create Date: 2022-09-06 21:03:17.069513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee440e418780'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_table('toolbox',
    sa.Column('toolbox_id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('toolbox_id')
    )
    op.create_table('tool',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('toolboxid', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=20), nullable=True),
    sa.Column('tool_brand', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['toolboxid'], ['toolbox.toolbox_id'], ),
    sa.PrimaryKeyConstraint('tool_id')
    )
    op.create_index(op.f('ix_tool_tool_brand'), 'tool', ['tool_brand'], unique=False)
    op.create_index(op.f('ix_tool_tool_name'), 'tool', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_tool_name'), table_name='tool')
    op.drop_index(op.f('ix_tool_tool_brand'), table_name='tool')
    op.drop_table('tool')
    op.drop_table('toolbox')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
